### ISSUE TITLE
The subtitles are also transparent

### ISSUE THREAD

**Issue by mojie126** [FranceBB/LinearTransformation#4]
I found vscude v1.1 version that supports x86
But the effect is like this: the originally opaque subtitles have become transparent
![微信截图_20231115133523](https://github.com/FranceBB/LinearTransformation/assets/7426101/ed9d390d-01a8-4361-9040-538b341e08b6)

**Comment by FranceBB** [comment]
I don't really understand what you're trying to accomplish here.
The fact that subtitles have also become transparent is the result of them being rendered by VSFilterMod this way in the alpha channel. If you don't want them to be transparent and in the alpha channel just use TextSub() or AssRender() to put them in the normal YUV or in the first 24bit of RGB (i.e RGB24).
I'm really failing to understand what you're trying to do.
I mean, in LinearTransformation() I'm applying the transformation on both luma and chroma of both the normal video and the alpha channel as they are, I mean as they're passed to me from the filter, so if they're rendered incorrectly in the first place, then it's a VSFilterMod problem.

For normal subs, however, in a non alpha channel, just render them with AssRender() and you're gonna be fine.

**Comment by FranceBB** [comment]
No problem, what you're looking for is either TextSub() or AssRender() then, but not MaskSubMod().

Bye,
Frank
